package proxy

// Note that this file was generated by `gb generate`.
// It should not be edited by hand.

//go:generate python ../../../../../scripts/generate_proxy_paths.py ../../../../../vendor/src/github.com/matrix-org/matrix-doc

import "regexp"

var unknownPath = "unknown path"

type regexpAndString struct {
	re *regexp.Regexp
	s  string
}

var (
	constantPaths = make(map[string]bool)
	regexpPaths   []regexpAndString
)

func endpointFor(path string) string {
	if ok := constantPaths[path]; ok {
		return path
	}
	for _, i := range regexpPaths {
		if i.re.MatchString(path) {
			return i.s
		}
	}
	return unknownPath
}

func init() {
	constantPaths[`/_matrix/client/api/v1/createRoom`] = true
	constantPaths[`/_matrix/client/api/v1/events`] = true
	constantPaths[`/_matrix/client/api/v1/initialSync`] = true
	constantPaths[`/_matrix/client/api/v1/login`] = true
	constantPaths[`/_matrix/client/api/v1/publicRooms`] = true
	constantPaths[`/_matrix/client/api/v1/pushers/set`] = true
	constantPaths[`/_matrix/client/api/v1/pushrules/`] = true
	constantPaths[`/_matrix/client/api/v1/search`] = true
	constantPaths[`/_matrix/client/api/v1/versions`] = true
	constantPaths[`/_matrix/client/api/v1/voip/turnServer`] = true
	constantPaths[`/_matrix/client/r0/account/3pid`] = true
	constantPaths[`/_matrix/client/r0/account/password`] = true
	constantPaths[`/_matrix/client/r0/createRoom`] = true
	constantPaths[`/_matrix/client/r0/events`] = true
	constantPaths[`/_matrix/client/r0/initialSync`] = true
	constantPaths[`/_matrix/client/r0/login`] = true
	constantPaths[`/_matrix/client/r0/publicRooms`] = true
	constantPaths[`/_matrix/client/r0/pushers/set`] = true
	constantPaths[`/_matrix/client/r0/pushrules/`] = true
	constantPaths[`/_matrix/client/r0/register`] = true
	constantPaths[`/_matrix/client/r0/search`] = true
	constantPaths[`/_matrix/client/r0/sync`] = true
	constantPaths[`/_matrix/client/r0/tokenrefresh`] = true
	constantPaths[`/_matrix/client/r0/versions`] = true
	constantPaths[`/_matrix/client/r0/voip/turnServer`] = true
	constantPaths[`/_matrix/client/v2_alpha/account/3pid`] = true
	constantPaths[`/_matrix/client/v2_alpha/account/password`] = true
	constantPaths[`/_matrix/client/v2_alpha/register`] = true
	constantPaths[`/_matrix/client/v2_alpha/sync`] = true
	constantPaths[`/_matrix/client/v2_alpha/tokenrefresh`] = true
	constantPaths[`/_matrix/media/api/v1/upload`] = true
	constantPaths[`/_matrix/media/r0/upload`] = true

	regexpPaths = append(regexpPaths, regexpAndString{regexp.MustCompile(`^/_matrix/client/api/v1/admin/whois/[^/]*$`), `/_matrix/client/api/v1/admin/whois/_`})
	regexpPaths = append(regexpPaths, regexpAndString{regexp.MustCompile(`^/_matrix/client/api/v1/events/[^/]*$`), `/_matrix/client/api/v1/events/_`})
	regexpPaths = append(regexpPaths, regexpAndString{regexp.MustCompile(`^/_matrix/client/api/v1/join/[^/]*$`), `/_matrix/client/api/v1/join/_`})
	regexpPaths = append(regexpPaths, regexpAndString{regexp.MustCompile(`^/_matrix/client/api/v1/presence/[^/]*/status$`), `/_matrix/client/api/v1/presence/_/status`})
	regexpPaths = append(regexpPaths, regexpAndString{regexp.MustCompile(`^/_matrix/client/api/v1/presence/list/[^/]*$`), `/_matrix/client/api/v1/presence/list/_`})
	regexpPaths = append(regexpPaths, regexpAndString{regexp.MustCompile(`^/_matrix/client/api/v1/profile/[^/]*$`), `/_matrix/client/api/v1/profile/_`})
	regexpPaths = append(regexpPaths, regexpAndString{regexp.MustCompile(`^/_matrix/client/api/v1/profile/[^/]*/avatar_url$`), `/_matrix/client/api/v1/profile/_/avatar_url`})
	regexpPaths = append(regexpPaths, regexpAndString{regexp.MustCompile(`^/_matrix/client/api/v1/profile/[^/]*/displayname$`), `/_matrix/client/api/v1/profile/_/displayname`})
	regexpPaths = append(regexpPaths, regexpAndString{regexp.MustCompile(`^/_matrix/client/api/v1/pushrules/[^/]*/[^/]*/[^/]*$`), `/_matrix/client/api/v1/pushrules/_/_/_`})
	regexpPaths = append(regexpPaths, regexpAndString{regexp.MustCompile(`^/_matrix/client/api/v1/pushrules/[^/]*/[^/]*/[^/]*/enabled$`), `/_matrix/client/api/v1/pushrules/_/_/_/enabled`})
	regexpPaths = append(regexpPaths, regexpAndString{regexp.MustCompile(`^/_matrix/client/api/v1/room/[^/]*$`), `/_matrix/client/api/v1/room/_`})
	regexpPaths = append(regexpPaths, regexpAndString{regexp.MustCompile(`^/_matrix/client/api/v1/rooms/[^/]*$`), `/_matrix/client/api/v1/rooms/_`})
	regexpPaths = append(regexpPaths, regexpAndString{regexp.MustCompile(`^/_matrix/client/api/v1/rooms/[^/]*/ban$`), `/_matrix/client/api/v1/rooms/_/ban`})
	regexpPaths = append(regexpPaths, regexpAndString{regexp.MustCompile(`^/_matrix/client/api/v1/rooms/[^/]*/context/[^/]*$`), `/_matrix/client/api/v1/rooms/_/context/_`})
	regexpPaths = append(regexpPaths, regexpAndString{regexp.MustCompile(`^/_matrix/client/api/v1/rooms/[^/]*/forget$`), `/_matrix/client/api/v1/rooms/_/forget`})
	regexpPaths = append(regexpPaths, regexpAndString{regexp.MustCompile(`^/_matrix/client/api/v1/rooms/[^/]*/initialSync$`), `/_matrix/client/api/v1/rooms/_/initialSync`})
	regexpPaths = append(regexpPaths, regexpAndString{regexp.MustCompile(`^/_matrix/client/api/v1/rooms/[^/]*/invite$`), `/_matrix/client/api/v1/rooms/_/invite`})
	regexpPaths = append(regexpPaths, regexpAndString{regexp.MustCompile(`^/_matrix/client/api/v1/rooms/[^/]*/invite $`), `/_matrix/client/api/v1/rooms/_/invite `})
	regexpPaths = append(regexpPaths, regexpAndString{regexp.MustCompile(`^/_matrix/client/api/v1/rooms/[^/]*/join$`), `/_matrix/client/api/v1/rooms/_/join`})
	regexpPaths = append(regexpPaths, regexpAndString{regexp.MustCompile(`^/_matrix/client/api/v1/rooms/[^/]*/kick$`), `/_matrix/client/api/v1/rooms/_/kick`})
	regexpPaths = append(regexpPaths, regexpAndString{regexp.MustCompile(`^/_matrix/client/api/v1/rooms/[^/]*/leave$`), `/_matrix/client/api/v1/rooms/_/leave`})
	regexpPaths = append(regexpPaths, regexpAndString{regexp.MustCompile(`^/_matrix/client/api/v1/rooms/[^/]*/members$`), `/_matrix/client/api/v1/rooms/_/members`})
	regexpPaths = append(regexpPaths, regexpAndString{regexp.MustCompile(`^/_matrix/client/api/v1/rooms/[^/]*/messages$`), `/_matrix/client/api/v1/rooms/_/messages`})
	regexpPaths = append(regexpPaths, regexpAndString{regexp.MustCompile(`^/_matrix/client/api/v1/rooms/[^/]*/redact/[^/]*/[^/]*$`), `/_matrix/client/api/v1/rooms/_/redact/_/_`})
	regexpPaths = append(regexpPaths, regexpAndString{regexp.MustCompile(`^/_matrix/client/api/v1/rooms/[^/]*/send/[^/]*/[^/]*$`), `/_matrix/client/api/v1/rooms/_/send/_/_`})
	regexpPaths = append(regexpPaths, regexpAndString{regexp.MustCompile(`^/_matrix/client/api/v1/rooms/[^/]*/state$`), `/_matrix/client/api/v1/rooms/_/state`})
	regexpPaths = append(regexpPaths, regexpAndString{regexp.MustCompile(`^/_matrix/client/api/v1/rooms/[^/]*/state/[^/]*$`), `/_matrix/client/api/v1/rooms/_/state/_`})
	regexpPaths = append(regexpPaths, regexpAndString{regexp.MustCompile(`^/_matrix/client/api/v1/rooms/[^/]*/state/[^/]*/[^/]*$`), `/_matrix/client/api/v1/rooms/_/state/_/_`})
	regexpPaths = append(regexpPaths, regexpAndString{regexp.MustCompile(`^/_matrix/client/api/v1/rooms/[^/]*/typing/[^/]*$`), `/_matrix/client/api/v1/rooms/_/typing/_`})
	regexpPaths = append(regexpPaths, regexpAndString{regexp.MustCompile(`^/_matrix/client/api/v1/rooms/[^/]*/unban$`), `/_matrix/client/api/v1/rooms/_/unban`})
	regexpPaths = append(regexpPaths, regexpAndString{regexp.MustCompile(`^/_matrix/client/api/v1/transactions/[^/]*$`), `/_matrix/client/api/v1/transactions/_`})
	regexpPaths = append(regexpPaths, regexpAndString{regexp.MustCompile(`^/_matrix/client/r0/admin/whois/[^/]*$`), `/_matrix/client/r0/admin/whois/_`})
	regexpPaths = append(regexpPaths, regexpAndString{regexp.MustCompile(`^/_matrix/client/r0/events/[^/]*$`), `/_matrix/client/r0/events/_`})
	regexpPaths = append(regexpPaths, regexpAndString{regexp.MustCompile(`^/_matrix/client/r0/join/[^/]*$`), `/_matrix/client/r0/join/_`})
	regexpPaths = append(regexpPaths, regexpAndString{regexp.MustCompile(`^/_matrix/client/r0/presence/[^/]*/status$`), `/_matrix/client/r0/presence/_/status`})
	regexpPaths = append(regexpPaths, regexpAndString{regexp.MustCompile(`^/_matrix/client/r0/presence/list/[^/]*$`), `/_matrix/client/r0/presence/list/_`})
	regexpPaths = append(regexpPaths, regexpAndString{regexp.MustCompile(`^/_matrix/client/r0/profile/[^/]*$`), `/_matrix/client/r0/profile/_`})
	regexpPaths = append(regexpPaths, regexpAndString{regexp.MustCompile(`^/_matrix/client/r0/profile/[^/]*/avatar_url$`), `/_matrix/client/r0/profile/_/avatar_url`})
	regexpPaths = append(regexpPaths, regexpAndString{regexp.MustCompile(`^/_matrix/client/r0/profile/[^/]*/displayname$`), `/_matrix/client/r0/profile/_/displayname`})
	regexpPaths = append(regexpPaths, regexpAndString{regexp.MustCompile(`^/_matrix/client/r0/pushrules/[^/]*/[^/]*/[^/]*$`), `/_matrix/client/r0/pushrules/_/_/_`})
	regexpPaths = append(regexpPaths, regexpAndString{regexp.MustCompile(`^/_matrix/client/r0/pushrules/[^/]*/[^/]*/[^/]*/enabled$`), `/_matrix/client/r0/pushrules/_/_/_/enabled`})
	regexpPaths = append(regexpPaths, regexpAndString{regexp.MustCompile(`^/_matrix/client/r0/room/[^/]*$`), `/_matrix/client/r0/room/_`})
	regexpPaths = append(regexpPaths, regexpAndString{regexp.MustCompile(`^/_matrix/client/r0/rooms/[^/]*$`), `/_matrix/client/r0/rooms/_`})
	regexpPaths = append(regexpPaths, regexpAndString{regexp.MustCompile(`^/_matrix/client/r0/rooms/[^/]*/ban$`), `/_matrix/client/r0/rooms/_/ban`})
	regexpPaths = append(regexpPaths, regexpAndString{regexp.MustCompile(`^/_matrix/client/r0/rooms/[^/]*/context/[^/]*$`), `/_matrix/client/r0/rooms/_/context/_`})
	regexpPaths = append(regexpPaths, regexpAndString{regexp.MustCompile(`^/_matrix/client/r0/rooms/[^/]*/forget$`), `/_matrix/client/r0/rooms/_/forget`})
	regexpPaths = append(regexpPaths, regexpAndString{regexp.MustCompile(`^/_matrix/client/r0/rooms/[^/]*/initialSync$`), `/_matrix/client/r0/rooms/_/initialSync`})
	regexpPaths = append(regexpPaths, regexpAndString{regexp.MustCompile(`^/_matrix/client/r0/rooms/[^/]*/invite$`), `/_matrix/client/r0/rooms/_/invite`})
	regexpPaths = append(regexpPaths, regexpAndString{regexp.MustCompile(`^/_matrix/client/r0/rooms/[^/]*/invite $`), `/_matrix/client/r0/rooms/_/invite `})
	regexpPaths = append(regexpPaths, regexpAndString{regexp.MustCompile(`^/_matrix/client/r0/rooms/[^/]*/join$`), `/_matrix/client/r0/rooms/_/join`})
	regexpPaths = append(regexpPaths, regexpAndString{regexp.MustCompile(`^/_matrix/client/r0/rooms/[^/]*/kick$`), `/_matrix/client/r0/rooms/_/kick`})
	regexpPaths = append(regexpPaths, regexpAndString{regexp.MustCompile(`^/_matrix/client/r0/rooms/[^/]*/leave$`), `/_matrix/client/r0/rooms/_/leave`})
	regexpPaths = append(regexpPaths, regexpAndString{regexp.MustCompile(`^/_matrix/client/r0/rooms/[^/]*/members$`), `/_matrix/client/r0/rooms/_/members`})
	regexpPaths = append(regexpPaths, regexpAndString{regexp.MustCompile(`^/_matrix/client/r0/rooms/[^/]*/messages$`), `/_matrix/client/r0/rooms/_/messages`})
	regexpPaths = append(regexpPaths, regexpAndString{regexp.MustCompile(`^/_matrix/client/r0/rooms/[^/]*/receipt/[^/]*/[^/]*$`), `/_matrix/client/r0/rooms/_/receipt/_/_`})
	regexpPaths = append(regexpPaths, regexpAndString{regexp.MustCompile(`^/_matrix/client/r0/rooms/[^/]*/redact/[^/]*/[^/]*$`), `/_matrix/client/r0/rooms/_/redact/_/_`})
	regexpPaths = append(regexpPaths, regexpAndString{regexp.MustCompile(`^/_matrix/client/r0/rooms/[^/]*/send/[^/]*/[^/]*$`), `/_matrix/client/r0/rooms/_/send/_/_`})
	regexpPaths = append(regexpPaths, regexpAndString{regexp.MustCompile(`^/_matrix/client/r0/rooms/[^/]*/state$`), `/_matrix/client/r0/rooms/_/state`})
	regexpPaths = append(regexpPaths, regexpAndString{regexp.MustCompile(`^/_matrix/client/r0/rooms/[^/]*/state/[^/]*$`), `/_matrix/client/r0/rooms/_/state/_`})
	regexpPaths = append(regexpPaths, regexpAndString{regexp.MustCompile(`^/_matrix/client/r0/rooms/[^/]*/state/[^/]*/[^/]*$`), `/_matrix/client/r0/rooms/_/state/_/_`})
	regexpPaths = append(regexpPaths, regexpAndString{regexp.MustCompile(`^/_matrix/client/r0/rooms/[^/]*/typing/[^/]*$`), `/_matrix/client/r0/rooms/_/typing/_`})
	regexpPaths = append(regexpPaths, regexpAndString{regexp.MustCompile(`^/_matrix/client/r0/rooms/[^/]*/unban$`), `/_matrix/client/r0/rooms/_/unban`})
	regexpPaths = append(regexpPaths, regexpAndString{regexp.MustCompile(`^/_matrix/client/r0/transactions/[^/]*$`), `/_matrix/client/r0/transactions/_`})
	regexpPaths = append(regexpPaths, regexpAndString{regexp.MustCompile(`^/_matrix/client/r0/user/[^/]*/account_data/[^/]*$`), `/_matrix/client/r0/user/_/account_data/_`})
	regexpPaths = append(regexpPaths, regexpAndString{regexp.MustCompile(`^/_matrix/client/r0/user/[^/]*/filter$`), `/_matrix/client/r0/user/_/filter`})
	regexpPaths = append(regexpPaths, regexpAndString{regexp.MustCompile(`^/_matrix/client/r0/user/[^/]*/filter/[^/]*$`), `/_matrix/client/r0/user/_/filter/_`})
	regexpPaths = append(regexpPaths, regexpAndString{regexp.MustCompile(`^/_matrix/client/r0/user/[^/]*/rooms/[^/]*/account_data/[^/]*$`), `/_matrix/client/r0/user/_/rooms/_/account_data/_`})
	regexpPaths = append(regexpPaths, regexpAndString{regexp.MustCompile(`^/_matrix/client/r0/user/[^/]*/rooms/[^/]*/tags$`), `/_matrix/client/r0/user/_/rooms/_/tags`})
	regexpPaths = append(regexpPaths, regexpAndString{regexp.MustCompile(`^/_matrix/client/r0/user/[^/]*/rooms/[^/]*/tags/[^/]*$`), `/_matrix/client/r0/user/_/rooms/_/tags/_`})
	regexpPaths = append(regexpPaths, regexpAndString{regexp.MustCompile(`^/_matrix/client/r0/users/[^/]*$`), `/_matrix/client/r0/users/_`})
	regexpPaths = append(regexpPaths, regexpAndString{regexp.MustCompile(`^/_matrix/client/v2_alpha/rooms/[^/]*/receipt/[^/]*/[^/]*$`), `/_matrix/client/v2_alpha/rooms/_/receipt/_/_`})
	regexpPaths = append(regexpPaths, regexpAndString{regexp.MustCompile(`^/_matrix/client/v2_alpha/user/[^/]*/account_data/[^/]*$`), `/_matrix/client/v2_alpha/user/_/account_data/_`})
	regexpPaths = append(regexpPaths, regexpAndString{regexp.MustCompile(`^/_matrix/client/v2_alpha/user/[^/]*/filter$`), `/_matrix/client/v2_alpha/user/_/filter`})
	regexpPaths = append(regexpPaths, regexpAndString{regexp.MustCompile(`^/_matrix/client/v2_alpha/user/[^/]*/filter/[^/]*$`), `/_matrix/client/v2_alpha/user/_/filter/_`})
	regexpPaths = append(regexpPaths, regexpAndString{regexp.MustCompile(`^/_matrix/client/v2_alpha/user/[^/]*/rooms/[^/]*/account_data/[^/]*$`), `/_matrix/client/v2_alpha/user/_/rooms/_/account_data/_`})
	regexpPaths = append(regexpPaths, regexpAndString{regexp.MustCompile(`^/_matrix/client/v2_alpha/user/[^/]*/rooms/[^/]*/tags$`), `/_matrix/client/v2_alpha/user/_/rooms/_/tags`})
	regexpPaths = append(regexpPaths, regexpAndString{regexp.MustCompile(`^/_matrix/client/v2_alpha/user/[^/]*/rooms/[^/]*/tags/[^/]*$`), `/_matrix/client/v2_alpha/user/_/rooms/_/tags/_`})
	regexpPaths = append(regexpPaths, regexpAndString{regexp.MustCompile(`^/_matrix/client/v2_alpha/users/[^/]*$`), `/_matrix/client/v2_alpha/users/_`})
	regexpPaths = append(regexpPaths, regexpAndString{regexp.MustCompile(`^/_matrix/media/api/v1/download/[^/]*/[^/]*$`), `/_matrix/media/api/v1/download/_/_`})
	regexpPaths = append(regexpPaths, regexpAndString{regexp.MustCompile(`^/_matrix/media/api/v1/thumbnail/[^/]*/[^/]*$`), `/_matrix/media/api/v1/thumbnail/_/_`})
	regexpPaths = append(regexpPaths, regexpAndString{regexp.MustCompile(`^/_matrix/media/r0/download/[^/]*/[^/]*$`), `/_matrix/media/r0/download/_/_`})
	regexpPaths = append(regexpPaths, regexpAndString{regexp.MustCompile(`^/_matrix/media/r0/thumbnail/[^/]*/[^/]*$`), `/_matrix/media/r0/thumbnail/_/_`})
}
